# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=200)),
                ('comentarios', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.Empleado')),
            ],
        ),
    ]
